In [4]:
import quandl
quandl.ApiConfig.api_key = "idNBU8ZQFvkUE9fDgWyz"
import numpy as np
import pandas as pd

In [5]:
prices = quandl.get_table('SHARADAR/SEP', ticker=['AAPL', 'KO', 'NKE', 'TSLA', 'XOM'], date={'gte':'2017-01-01', 'lte':'2018-12-31'}, paginate=True)

In [6]:
prices.head()

,ticker,date,open,high,low,close,volume,dividends,closeunadj,lastupdated
None,,,,,,,,,,
0,XOM,2018-12-31,68.32,69.145,67.66,68.19,15609337.0,0.0,68.19,2018-12-31
1,XOM,2018-12-28,69.18,69.580,67.82,68.17,19617793.0,0.0,68.17,2018-12-28
2,XOM,2018-12-27,67.74,68.940,66.08,68.94,21315318.0,0.0,68.94,2018-12-27
3,XOM,2018-12-26,66.18,68.655,64.65,68.64,24403048.0,0.0,68.64,2018-12-26
4,XOM,2018-12-24,66.87,67.530,65.44,65.51,14262074.0,0.0,65.51,2018-12-28

In [4]:
pivoted = prices.pivot(index='date', columns='ticker', values='close')
pivoted.head()

ticker        AAPL     KO    NKE    TSLA    XOM
date
2018-09-04  228.36  44.76  79.60  288.95  80.29
2018-09-05  226.87  45.38  79.92  280.74  81.36
2018-09-06  223.10  45.77  80.40  280.95  80.46
2018-09-07  221.30  45.72  80.30  263.24  81.83
2018-09-10  218.33  46.06  82.10  285.50  81.71

In [5]:
pivoted.pct_change()

ticker          AAPL        KO       NKE      TSLA       XOM
date
2017-01-03       NaN       NaN       NaN       NaN       NaN
2017-01-04 -0.001119 -0.003589  0.020970  0.046085 -0.011002
2017-01-05  0.005085  0.002401 -0.000188 -0.001057 -0.014907
2017-01-06  0.011148 -0.000240  0.016020  0.009967 -0.000565
2017-01-09  0.009160 -0.010062 -0.009831  0.009912 -0.016497
2017-01-10  0.001008 -0.006776 -0.005058 -0.006097 -0.012753
2017-01-11  0.005373  0.000244 -0.007908 -0.000609  0.010241
2017-01-12 -0.004175 -0.002436 -0.005504 -0.000609 -0.005414
2017-01-13 -0.001761 -0.001709  0.009924  0.035542  0.000116
2017-01-17  0.008065  0.008317  0.013794 -0.009127  0.011697
2017-01-18 -0.000083  0.001698 -0.007083  0.011801 -0.012363
2017-01-19 -0.001750 -0.003633 -0.006383  0.022655 -0.017965
2017-01-20  0.001837  0.004375  0.005101  0.003979  0.013691
2017-01-23  0.000667  0.002662  0.000752  0.017121 -0.010711
2017-01-24 -0.000916  0.011344  0.003944  0.022859  0.001412
2017-01-25  0.015921  0.005251  0.007671 -0.000550  0.002938
2017-01-26  0.000492 -0.007360 -0.003899 -0.007702  0.003047
2017-01-27  0.000082 -0.008610 -0.008574  0.001743 -0.001051
2017-01-30 -0.002624 -0.001689 -0.002068 -0.009172 -0.007601
2017-01-31 -0.002302  0.004592 -0.003391  0.005187 -0.011431
2017-02-01  0.060981 -0.007457  0.002268 -0.010678 -0.011324
2017-02-02 -0.001709  0.003393 -0.004149  0.009268  0.006149
2017-02-03  0.004279  0.003382 -0.008333 -0.000875  0.001078
2017-02-06  0.009374  0.000481  0.008403  0.025624 -0.002753
2017-02-07  0.009517  0.008181  0.000189 -0.001125 -0.006482
2017-02-08  0.003877  0.002864  0.020261  0.017865 -0.015585
2017-02-09  0.002878 -0.018325  0.026540  0.027167  0.004418
2017-02-10 -0.002266 -0.016242  0.016453  0.000111  0.008309
2017-02-13  0.008856  0.000986 -0.002312  0.042232  0.005817
2017-02-14  0.012979 -0.002216  0.006418  0.001354 -0.002169
...              ...       ...       ...       ...       ...
2018-11-15  0.024679 -0.000402 -0.011569  0.012907  0.010337
2018-11-16  0.011076  0.008645  0.005516  0.016847  0.009848
2018-11-19 -0.039632  0.006777 -0.029703 -0.002371  0.003293
2018-11-20 -0.047778 -0.022372 -0.019305 -0.016918 -0.028402
2018-11-21 -0.001130 -0.013163  0.017576 -0.026763  0.007665
2018-11-23 -0.025399  0.005951 -0.012160 -0.036548 -0.026689
2018-11-26  0.013524 -0.003060  0.017065  0.061903  0.019738
2018-11-27 -0.002176  0.010231 -0.008527 -0.006012  0.000909
2018-11-28  0.038453  0.006887  0.035650  0.011485  0.018170
2018-11-29 -0.007682 -0.014685 -0.004286 -0.019260  0.007776
2018-11-30 -0.005402  0.028991  0.010492  0.027288  0.005565
2018-12-03  0.034942 -0.014087  0.037540  0.022854  0.021635
2018-12-04 -0.043989 -0.002214 -0.027585  0.003375 -0.022039
2018-12-06 -0.011149 -0.004034 -0.003299  0.009341 -0.013093
2018-12-07 -0.035657 -0.005873 -0.029124 -0.014033 -0.009568
2018-12-10  0.006588  0.003056 -0.011317  0.020072 -0.014168
2018-12-11 -0.005719  0.006093  0.014619  0.004409  0.001829
2018-12-12  0.002787 -0.006459  0.010194 -0.000436 -0.008607
2018-12-13  0.010940  0.005079 -0.018703  0.027796  0.012628
2018-12-14 -0.031998 -0.002628 -0.005485 -0.029406 -0.018187
2018-12-17 -0.009306 -0.020470 -0.036261 -0.047278 -0.020376
2018-12-18  0.012993 -0.000207  0.017883 -0.032690 -0.027553
2018-12-19 -0.031192 -0.008692 -0.030639 -0.012046 -0.016944
2018-12-20 -0.025235 -0.007516 -0.020879 -0.052828 -0.030376
2018-12-21 -0.038896  0.000631  0.071672  0.013920 -0.007431
2018-12-24 -0.025874 -0.033845 -0.059002 -0.076242 -0.038315
2018-12-26  0.070422  0.021323  0.072100  0.103930  0.047779
2018-12-27 -0.006490  0.012569  0.009040 -0.030544  0.004371
2018-12-28  0.000512 -0.006943 -0.004479  0.056116 -0.011169
2018-12-31  0.009665  0.003178  0.010908 -0.003205  0.000293

[502 rows x 5 columns]